version: '3'
services:
  backend:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST_POSTGRES=${DB_HOST_POSTGRES}
      - DB_PORT_POSTGRES=${DB_PORT_POSTGRES}
      - DB_HOST_MONGO=${DB_HOST_MONGO}
      - DB_PORT_MONGO=${DB_PORT_MONGO}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb
      - redis

  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: redsocial
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6.0.6
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7.0.11
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  mongo-data: